name: dart56
description: Base 56 library for converting base10 and base8 numbers to/from base56 for readable and HTML-ID safe sequences
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqlite3: ^2.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0